site_name: vTaskr Backend
site_description: vTaskr Backend Developer Documentation
site_url: https://valbou.github.io/vtaskr-backend/
remote_branch: gh-pages
repo_url: https://github.com/Valbou/vtaskr-frontend
repo_name: GitHub
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - About: about.md
plugins:
  - search
  - mermaid2
