"""empty message

Revision ID: 2442f2f9fe5a
Revises: 3f8109669706
Create Date: 2024-06-23 11:46:39.351744

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "2442f2f9fe5a"
down_revision = "3f8109669706"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "groups",
        sa.Column("description", sa.String(), server_default="", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("groups", "description")
    # ### end Alembic commands ###
