"""empty message

Revision ID: 3f8109669706
Revises: cd34a3bc55a9
Create Date: 2024-05-29 18:55:47.455802

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "3f8109669706"
down_revision = "cd34a3bc55a9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("groups", sa.Column("is_private", sa.Boolean(), nullable=True))
    op.create_table(
        "invitations",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("from_user_id", sa.String(length=40), nullable=False),
        sa.Column("in_group_id", sa.String(length=40), nullable=False),
        sa.Column("with_roletype_id", sa.String(length=40), nullable=False),
        sa.Column("to_user_email", sa.String(length=250), nullable=True),
        sa.Column("hash", sa.String(length=130), nullable=True),
        sa.ForeignKeyConstraint(
            ["from_user_id"],
            ["users.id"],
            name="fk_invitations_user_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["in_group_id"],
            ["groups.id"],
            name="fk_invitations_group_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["with_roletype_id"],
            ["roletypes.id"],
            name="fk_invitations_roletype_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_index("subscriptions_events_contact_id_index", table_name="subscriptions")
    op.create_index(
        "subscriptions_events_contact_index",
        "subscriptions",
        ["event_name", "event_type", "contact_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("subscriptions_events_contact_index", table_name="subscriptions")
    op.create_index(
        "subscriptions_events_contact_id_index",
        "subscriptions",
        ["event_name", "event_type", "contact_id"],
        unique=False,
    )
    op.drop_table("invitations")
    op.drop_column("groups", "is_private")
    # ### end Alembic commands ###
