"""empty message

Revision ID: 5c61e6a268e0
Revises: 2442f2f9fe5a
Create Date: 2024-07-14 10:39:52.427296

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "5c61e6a268e0"
down_revision = "2442f2f9fe5a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_invitations_roletype_id", "invitations", type_="foreignkey")
    op.create_foreign_key(
        "fk_invitations_roletype_id",
        "invitations",
        "roletypes",
        ["with_roletype_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_invitations_roletype_id", "invitations", type_="foreignkey")
    op.create_foreign_key(
        "fk_invitations_roletype_id",
        "invitations",
        "roletypes",
        ["with_roletype_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
