"""add user assigned to

Revision ID: a56f90b2adf6
Revises: 5c61e6a268e0
Create Date: 2024-11-02 18:22:38.665030

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "a56f90b2adf6"
down_revision = "5c61e6a268e0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column("assigned_to", sa.String(), server_default="", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "assigned_to")
    # ### end Alembic commands ###
