"""initial

Revision ID: eb892f48dbd8
Revises:
Create Date: 2023-10-04 19:46:27.919877

"""
import sqlalchemy as sa

from alembic import op
from src.colors.persistence.sqlalchemy.color import ColorType
from src.users.persistence.sqlalchemy.tables.right_table import PermissionsType
from src.users.persistence.sqlalchemy.tables.user_table import LocaleField

# revision identifiers, used by Alembic.
revision = "eb892f48dbd8"
down_revision = None
branch_labels = None
depends_on = None

requesttype_enum = sa.Enum("EMAIL", "PASSWORD", name="requesttype")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "groups",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "requestschanges",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "request_type",
            requesttype_enum,
            nullable=False,
        ),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("code", sa.String(length=12), nullable=False),
        sa.Column("done", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.Column("color", ColorType(length=20), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(length=150), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("emergency", sa.Boolean(), nullable=False),
        sa.Column("important", sa.Boolean(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration", sa.Interval(), nullable=True),
        sa.Column("done", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(length=25), nullable=False),
        sa.Column("last_name", sa.String(length=25), nullable=False),
        sa.Column("email", sa.String(length=250), nullable=False),
        sa.Column("hash_password", sa.String(length=256), nullable=True),
        sa.Column("locale", LocaleField(length=5), nullable=True),
        sa.Column("timezone", sa.String(length=35), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "roletypes",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("group_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
            name="fk_roletypes_group_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "group_id", name="roletype_name_group"),
    )
    op.create_index(
        "roletype_name_group_index", "roletypes", ["name", "group_id"], unique=False
    )
    op.create_table(
        "taskstags",
        sa.Column("tag_id", sa.String(), nullable=False),
        sa.Column("task_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], name="fk_taskstags_tag_id"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], name="fk_taskstags_task_id"),
        sa.PrimaryKeyConstraint("tag_id", "task_id"),
    )
    op.create_table(
        "tokens",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("temp", sa.Boolean(), nullable=False),
        sa.Column("temp_code", sa.String(length=12), nullable=True),
        sa.Column("sha_token", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_tokens_user_id", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sha_token"),
    )
    op.create_table(
        "rights",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("roletype_id", sa.String(), nullable=False),
        sa.Column("resource", sa.String(length=80), nullable=False),
        sa.Column("permissions", PermissionsType(), nullable=False),
        sa.ForeignKeyConstraint(
            ["roletype_id"],
            ["roletypes.id"],
            name="fk_rights_roletype_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("roletype_id", "resource", name="right_roletype_resource"),
    )
    op.create_index(
        "right_roletype_resource_index",
        "rights",
        ["roletype_id", "resource"],
        unique=False,
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("group_id", sa.String(), nullable=False),
        sa.Column("roletype_id", sa.String(), nullable=False),
        sa.Column("color", ColorType(length=20), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"], ["groups.id"], name="fk_roles_group_id", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["roletype_id"],
            ["roletypes.id"],
            name="fk_roles_roletype_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_roles_user_id", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "group_id", name="role_user_group"),
    )
    op.create_index(
        "role_user_group_index", "roles", ["user_id", "group_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("role_user_group_index", table_name="roles")
    op.drop_table("roles")
    op.drop_index("right_roletype_resource_index", table_name="rights")
    op.drop_table("rights")
    op.drop_table("tokens")
    op.drop_table("taskstags")
    op.drop_index("roletype_name_group_index", table_name="roletypes")
    op.drop_table("roletypes")
    op.drop_table("users")
    op.drop_table("tasks")
    op.drop_table("tags")
    op.drop_table("requestschanges")
    op.drop_table("groups")
    requesttype_enum.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
